import type { Metadata } from "next";
import "./globals.css";
import Header from "./pages/Header";
import Sidebar from "./pages/Sidebar";

export const metadata: Metadata = {
  title: "Kanban Task Management",
  description: "Generated by Kuxala",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: any;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <div className="flex">
          <Sidebar />
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
