import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: "400", // or any other valid value or array of values
});

export const metadata: Metadata = {
  title: "Kanban Task Management",
  description: "Generated by Kuxala",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: any;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
